;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][StatusBar]
Pos=0,880
Size=1560,32
Collapsed=0

[Window][Performance]
Pos=0,721
Size=297,261
Collapsed=0
DockId=0x00000004,0

[Window][Point View Settings]
Pos=0,21
Size=297,860
Collapsed=0
DockId=0x00000003,0

[Window][Point View]
Pos=299,21
Size=1261,860
Collapsed=0
DockId=0x00000002,0

[Docking][Data]
DockSpace     ID=0xAFC85805 Window=0x079D3A04 Pos=0,21 Size=1560,860 Split=X Selected=0xA49EB8BE
  DockNode    ID=0x00000001 Parent=0xAFC85805 SizeRef=297,961 Split=Y Selected=0x408E2F7B
    DockNode  ID=0x00000003 Parent=0x00000001 SizeRef=268,698 Selected=0x408E2F7B
    DockNode  ID=0x00000004 Parent=0x00000001 SizeRef=268,261 Selected=0x726D8899
  DockNode    ID=0x00000002 Parent=0xAFC85805 SizeRef=1555,961 CentralNode=1 Selected=0xA49EB8BE

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[StatusBar]
Show=true
ShowFps=true
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{"MainDockSpace":2949142533}}
